### PR TITLE
Update to tokio v1.0

### PR DESCRIPTION
**Pull request by RAnders00**
See #71

### CODE REVIEW

**Review by ldesgoui — APPROVED** [review]

**Comment by pajlada** [comment]
https://github.com/egg-mode-rs/egg-mode/pull/111 :smiley:

**Comment by RAnders00** [comment]
Now waiting for https://github.com/egg-mode-rs/egg-mode/issues/112

**Comment by RAnders00** [comment]
I want to merge this now

**Comment by alazymeme** [comment]
ok

**Pull request merged**
